app/blueprints/admin/post/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectField, HiddenField
from wtforms.validators import ValidationError, DataRequired, Regexp, Length
from ....db import get_db


class UpdatePostForm(FlaskForm):
    def validate_slug(form, field):
        db = get_db()
        post = db.execute(
            'SELECT id, slug FROM post WHERE slug = ?', (field.data,)
        ).fetchone()
        if post is not None and int(post["id"]) != int(form.data["id"]):
            raise ValidationError('Slug exists. This field must be Unique')

    slug = StringField('Slug', validators=[DataRequired(),
                                           Regexp(regex=r'^[a-zA-Z0-9\-]+$', message='Must contain only Alphanumeric and Hyphen characters'),
                                           Length(max=128)])
    post_position = SelectField("Position", coerce=int)
    visible = SelectField("Visibile",  coerce=int)
    post = TextAreaField('Post Content', validators=[DataRequired()])
    id = HiddenField()


class CreatePostForm(FlaskForm):
    def validate_slug(form, field):
        db = get_db()
        slug = db.execute(
            'SELECT slug FROM post WHERE slug = ?', (field.data,)
        ).fetchone()
        if slug is not None:
            raise ValidationError('Slug exists. This field must be Unique')

    slug = StringField('Slug', validators=[DataRequired(), Regexp(
        regex=r'^[a-zA-Z0-9\-]+$', message='Must contain only Alphanumeric and Hyphen characters'), Length(max=128)])
    post = TextAreaField('Post Content', validators=[DataRequired()])

app/blueprints/admin/post/__init__.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort

from .forms import CreatePostForm, UpdatePostForm
from ..auth import login_required
from ....db import get_db


bp = Blueprint('post', __name__, url_prefix='/admin/post')


@bp.route('/', defaults={'id': None})
@bp.route('/<id>')
@login_required
def index(id):
    db = get_db()
    if id is None:
        posts = db.execute(
            'SELECT p.id, p.created, p.slug, p.visible, p.post_position, p.menu_name, p.menu_position, p.menu_visibility, u.user_name'
            ' FROM post p JOIN user u ON p.author_id = u.id'
            ' ORDER BY created DESC'
        ).fetchall()
        return render_template('views/admin/post/index.html', posts=posts)
    else:
        post = db.execute(
            'SELECT p.id, p.created, p.slug, p.visible, p.post_position, p.menu_name, p.menu_position, p.menu_visibility, u.user_name, p.post'
            ' FROM post p JOIN user u ON p.author_id = u.id'
            ' WHERE p.id = ?',
            (id,)
        ).fetchall()
        if len(post) == 0:
            abort(404)
        return render_template('views/admin/post/view.html', post=post[0])


@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    form = CreatePostForm()
    if form.validate_on_submit():
        slug = form.slug.data
        post = form.post.data
        db = get_db()
        row = db.execute(
            'SELECT MAX(post_position), MAX(menu_position) FROM post'
        ).fetchone()
        new_post_position = 1 if row[0] is None else row[0] + 1
        new_menu_position = 1 if row[1] is None else row[1] + 1
        cur = db.execute(
            'INSERT INTO post (slug, post, author_id, post_position, menu_position, visible, menu_visibility)'
            ' VALUES (?, ?, ?, ?, ?, ?, ?)',
            (slug, post, g.user['id'],
             new_post_position, new_menu_position, 0, 0)
        )
        db.commit()
        flash('Post created', 'success')
        return redirect(url_for('post.index', id=cur.lastrowid))
    return render_template('views/admin/post/create.html', form=form)


@bp.route('/update/<id>', methods=('GET', 'POST'))
@login_required
def update(id):
    db = get_db()
    post = db.execute(
        'SELECT p.id, p.created, p.slug, p.visible, p.post_position, p.menu_name, p.menu_position, p.menu_visibility, u.user_name, p.post'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' WHERE p.id = ?',
        (id,)
    ).fetchall()
    if len(post) == 0:
        abort(404)

    form = UpdatePostForm()
    form.post_position.choices = [
        [pp[0], pp[0]] for pp in
        db.execute(
            'SELECT DISTINCT post_position FROM post order by 1'
        ).fetchall()
    ]
    form.visible.choices = [(1, 'Yes'), (0, 'No')]

    if form.validate_on_submit():
        post_with_same_position = db.execute(
            'SELECT id FROM post WHERE post_position = ?',
            (form.post_position.data,)
        ).fetchone()

        if post_with_same_position is not None and post[0]["id"] != post_with_same_position[0]:
            db.execute(
                'UPDATE post SET post_position = ? WHERE id = ?',
                (post[0]["post_position"], post_with_same_position[0], )
            )
        db.execute(
            'UPDATE post SET slug = ?, post_position = ?, visible = ?, post = ?'
            ' WHERE id = ?',
            (form.slug.data, form.post_position.data,
             form.visible.data, form.post.data, form.id.data)
        )
        db.commit()
        flash('Post updated', 'success')
        return redirect(url_for('post.index', id=form.id.data))

    if request.method == 'GET':
        form.slug.data = post[0]["slug"]
        form.post_position.data = post[0]["post_position"]
        form.visible.data = post[0]["visible"]
        form.post.data = post[0]["post"]
        form.id.data = post[0]["id"]

    return render_template('views/admin/post/update.html', form=form)

app/templates/views/admin/post/create.html
{% extends 'views/admin/layouts/main/index.html' %}
{% from "macros/form_helpers.html" import render_field, render_form %}

{% block title %}
  Admin - Create Post
{% endblock %}

{% block header %}
  <h1 class="h4">Admin: Create Post</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <a href="{{url_for('post.index')}}" class="btn btn-sm btn-outline-secondary">Back</a>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="col-sm-12 col-md-10 col-lg-8">
    <form method="POST">
      {{render_form(form, "Save", "Reset")}}
    </form>  
  </div>
{% endblock %}

{% block tail %}
<!-- <script src="{{url_for('static', filename='js/tinymce/tinymce.min.js') }}"></script>
<script>
  $(document).ready(function(){
    tinymce.init({
      selector: '#post',
    });
  })
</script> -->
{% endblock %}

app/templates/views/admin/post/index.html
{% extends 'views/admin/layouts/main/index.html' %}
{% from 'macros/table_helpers.html' import render_table %}


{% block title %}
Admin - Posts
{% endblock %}

{% block header %}
  <h1 class="h4">Admin: Posts</h1>
  <div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <a href="{{url_for('post.create')}}" class="btn btn-sm btn-outline-secondary">Create</a>
    </div>
  </div>  
{% endblock %}


{% block content %}
  {% if posts %}
    {{ 
      render_table(
        posts,
        caption='Posts',
        responsive=true,
        table_classes='table-bordered table-striped table-hover table-sm',
        header_classes='thead-dark',
        show_actions=true,
        actions_title="Action",
        primary_key_title = "#",
        primary_key='id',
        actions = [
          {'route': 'post.index',  'route_variable': 'id', 'name': '', 'title': 'View', 'class':'btn btn-outline-dark btn-sm', 'icon':'file-text'},
          {'route': 'post.update', 'route_variable': 'id', 'name': '', 'title': 'Edit', 'class':'btn btn-outline-dark btn-sm', 'icon':'edit'}
        ],
        actions_pos = 'last',
        titles=[
          ('id',None), 
          ('created', 'Created'),
          ('slug', 'Slug'),
          ('visible', 'Visible'),
          ('post_position', 'Post Position'),
          ('menu_name', 'Menu name'),
          ('menu_position', 'Menu position'),
          ('menu_visibility', 'Menu visibility'),
          ('user_name', 'Author')
        ]
      )
    }}
  {% endif %}
{% endblock %}

app/templates/views/admin/post/update.html
{% extends 'views/admin/layouts/main/index.html' %}
{% from "macros/form_helpers.html" import render_field, render_form %}

{% block title %}
Admin - Update Post
{% endblock %}

{% block header %}
<h1 class="h4">Admin: Update Post</h1>
<div class="btn-toolbar mb-2 mb-md-0">
  <div class="btn-group mr-2">
    <a href="{{url_for('post.index')}}" class="btn btn-sm btn-outline-secondary">Post List</a>
    <a href="{{url_for('post.index',id=form.id.data )}}" class="btn btn-sm btn-secondary">Back</a>
  </div>
</div>
{% endblock %}

{% block content %}
  <div class="col-sm-12 col-md-10 col-lg-8">
    <form method="POST">
      {{render_form(form, "Save", "Reset")}}
    </form>  
  </div>
{% endblock %}

app/templates/views/admin/post/view.html
{% extends 'views/admin/layouts/main/index.html' %} 
{% from 'macros/table_helpers.html' import render_table %} 

{% block title %} Admin - Post {% endblock %} 
{% block header %}
<h1 class="h4">Admin: Post</h1>
<div class="btn-toolbar mb-2 mb-md-0">
    <div class="btn-group mr-2">
      <a href="{{url_for('post.index')}}" class="btn btn-sm btn-outline-secondary">Back</a>
      <a href="{{url_for('post.update',id=post['id'] )}}" class="btn btn-sm btn-secondary">Edit</a>
    </div>
  </div>
{% endblock %} 


{% block content %}
    <div class="card-deck">
        <div class="card mb-3" style="width: 100%">
            <h5 class="card-header">Post</h5>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>ID</strong> {{post["id"]}}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Author</strong> {{post["username"]}}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Created At</strong> {{post["created"]}}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Position</strong> {{post["post_position"]}}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Visible</strong> {{post["visible"]}}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Slug</strong> {{post["slug"]}}</li>
                </ul>
            </div>
        </div>
        <div class="card mb-3" style="width: 100%">
            <h5 class="card-header">Menu</h5>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Name</strong> {{post["menu_name"]}}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Position</strong> {{post["menu_position"]}}</li>
                    <li class="list-group-item d-flex justify-content-between align-items-center"><strong>Visible</strong> {{post["menu_visibility"]}}</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="card mb-3" style="width: 100%">
        <h5 class="card-header">Content</h5>
        <div class="card-body" style="padding:10px; width:100%;min-height:100px;">
           <div style="background-color:antiquewhite;padding:10px;">
                <code>
                    {{post['post']}}
                </code>
            </div>
        </div>
    </div>
{% endblock %}